import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/Components/Navigation/Navbar";
import { Footer } from "@/Components/Layouts/Footer";
import { Providers } from "./provider";
import { merriweather } from "@/public/fonts/layoutFont";
import "leaflet/dist/leaflet.css";



export const metadata: Metadata = {
  title: "Alpha Flight",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon/favicon1.png" />
      </head>
      <body className={`${merriweather.className} bg-page`}>
        <Providers>
          <Navbar />
          {children}
          {/* <Footer /> */}
        </Providers>
      </body>
    </html>
  );
}
